# Generated by Django 6.0.2 on 2026-05-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("concepts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawJobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=200, unique=True)),
                ("job_title", models.CharField(max_length=300)),
                ("employer_name", models.CharField(blank=True, max_length=300)),
                ("job_city", models.CharField(blank=True, max_length=200)),
                ("job_country", models.CharField(blank=True, max_length=10)),
                ("job_description", models.TextField()),
                ("job_posted_at", models.DateTimeField(blank=True, null=True)),
                ("job_min_salary", models.IntegerField(blank=True, null=True)),
                ("job_max_salary", models.IntegerField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["job_posted_at"], name="trends_rawj_job_pos_cef9d8_idx"
                    ),
                    models.Index(
                        fields=["fetched_at"], name="trends_rawj_fetched_3458bb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobTrend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trend_type",
                    models.CharField(
                        choices=[
                            ("skill", "Skill"),
                            ("role", "Job Role"),
                            ("company", "Company"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("count", models.PositiveIntegerField()),
                ("percentage", models.FloatField()),
                ("growth_7d", models.FloatField(blank=True, null=True)),
                ("snapshot_date", models.DateField()),
                ("sample_size", models.PositiveIntegerField()),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trends",
                        to="concepts.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_date", "trend_type", "-percentage"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_date", "trend_type"],
                        name="trends_jobt_snapsho_e5ee0e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trend_type", "name", "snapshot_date"),
                        name="unique_trend_per_snapshot",
                    )
                ],
            },
        ),
    ]
