# Generated by Django 6.0.2 on 2026-02-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerGapProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("employed", "Employed"),
                            ("unemployed", "Unemployed"),
                            ("freelancing", "Freelancing"),
                            ("studying", "Studying"),
                        ],
                        default="unemployed",
                        max_length=20,
                    ),
                ),
                ("education", models.CharField(max_length=50)),
                ("prior_experience", models.TextField(blank=True)),
                ("certifications", models.TextField(blank=True)),
                ("projects", models.TextField(blank=True)),
                ("portfolio", models.URLField(blank=True)),
                ("interests", models.CharField(blank=True, max_length=50)),
                ("gap_story", models.TextField(blank=True)),
                ("gap_duration", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
