# Generated by Django 6.0.2 on 2026-02-24 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_careergapprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(blank=True, max_length=50)),
                ("skills", models.TextField(blank=True)),
                ("company", models.CharField(blank=True, max_length=100)),
                ("years_of_experience", models.IntegerField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True)),
                ("interests", models.CharField(blank=True, max_length=200)),
                ("availability", models.BooleanField(default=True)),
                (
                    "availability_times",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Weekends 10am-12pm IST",
                        max_length=200,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
