# Generated by Django 6.0.2 on 2026-03-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_mentorprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="careergapprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
    ]
