# Generated by Django 6.0.2 on 2026-03-05 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0002_domain_jobrole_domain"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSkillAssessment",
        ),
    ]
