# Generated by Django 6.0.2 on 2026-03-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0003_delete_userskillassessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_skills",
                to="concepts.skillcategory",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="job_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_skills",
                to="concepts.jobrole",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
